<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zenika.tech-lab</groupId>
        <artifactId>tech-lab-ingester</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>common</artifactId>

    <build>
        <defaultGoal>verify</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <configuration>
                    <excludes>
                        <exclude>**/librariesio/model/*</exclude>
                        <exclude>**/ingester/model/*</exclude>
                        <exclude>**/github/model/*</exclude>
                        <exclude>**/stackoverflow/model/*</exclude>
                        <!-- Standard set of exclusions-->
                        <exclude>**/annotations/*</exclude>
                        <exclude>**/enums/*</exclude>
                        <exclude>**/exceptions/*</exclude>
                        <exclude>**/*.docx</exclude>
                        <exclude>**/*.xlsx</exclude>
                        <exclude>**/*.jks</exclude>
                        <exclude>**/*.png</exclude>
                        <exclude>**/*.ttf</exclude>
                        <exclude>**/*.woff</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <id>Jacoco - prepare agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>Jacoco - generate report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <phase>test</phase>
                    </execution>
                    <execution>
                        <id>Jacoco - is code covered?</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>verify</phase>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>INSTRUCTION</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>${jacoco.covered.instructions.target.percentage}</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <url>http://maven.apache.org</url>

</project>
